openapi: 3.0.0
info:
  title: API de Usuarios con Autenticación
  version: 1.0.0
  description: >
    API para gestión de usuarios con login, 2FA, recuperación de credenciales
    y administración de roles.
servers:
  - url: http://localhost:3000/api

paths:
  /users:
    get:
      summary: Lista todos los usuarios
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer }
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: integer }
                        email: { type: string }
                        role: { type: string }
                        phone: { type: string }

    post:
      summary: Crear un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - role
                - phone
              properties:
                email: { type: string }
                password: { type: string }
                role: 
                  type: string
                  enum: [admin, editor, lector, user]
                phone: { type: string }
      responses:
        '201':
          description: Usuario creado
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 0 }
                  message: { type: string }
                  user:
                    type: object
        '400':
          description: Error al crear usuario
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 1 }
                  message: { type: string }

  /users/{email}:
      put:
        summary: Actualiza un usuario por correo electrónico
        parameters:
          - in: path
            name: email
            required: true
            schema: { type: string }
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  newEmail: { type: string }
                  password: { type: string }
                  role: 
                    type: string
                    enum: [admin, editor, lector, user]
                  phone: { type: string }
        responses:
          '200':
            description: Usuario actualizado
          '404':
            description: Usuario no encontrado

      delete:
        summary: Elimina un usuario por correo electrónico
        parameters:
          - in: path
            name: email
            required: true
            schema: { type: string }
        responses:
          '200':
            description: Usuario eliminado
          '404':
            description: Usuario no encontrado

  /auth/login:
    post:
      summary: Login de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200':
          description: Login exitoso o requiere 2FA
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 0 }
                  message: { type: string }
                  requires2fa: { type: boolean }
                  token: { type: string }
        '401':
          description: Credenciales inválidas
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 1 }
                  message: { type: string }

  /auth/2fa/verify:
    post:
      summary: Verifica código OTP del 2FA
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tempToken, otp]
              properties:
                tempToken: { type: string }
                otp: { type: string }
      responses:
        '200':
          description: 2FA verificado
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 0 }
                  message: { type: string }
                  token: { type: string }
        '400':
          description: OTP inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 1 }
                  message: { type: string }

  /auth/password-reset/request:
    post:
      summary: Solicitar restablecimiento de contraseña
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email: { type: string }
                via: 
                  type: string
                  enum: [email, sms]
      responses:
        '200':
          description: Instrucciones enviadas
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 0 }
                  message: { type: string }

  /auth/password-reset/confirm:
    post:
      summary: Confirmar restablecimiento de contraseña
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token: { type: string }
                newPassword: { type: string }
      responses:
        '200':
          description: Contraseña cambiada
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 0 }
                  message: { type: string }
        '400':
          description: Token/OTP inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 1 }
                  message: { type: string }

  /auth/recover-username:
    post:
      summary: Recuperar nombre de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [emailOrPhone]
              properties:
                emailOrPhone: { type: string }
      responses:
        '200':
          description: Si existe, se envía username por email o SMS
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 0 }
                  message: { type: string }
  
  /auth/verify-offline:
    post:
      summary: Verifica PIN offline para login sin internet
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - offlinePin
                - lat
                - lng
              properties:
                userId:
                  type: number
                  example: 42
                offlinePin:
                  type: string
                  example: "829705"
                lat:
                  type: number
                  example: 19.4326
                lng:
                  type: number
                  example: -99.1332
      responses:
        '200':
          description: Login offline exitoso
          content:
            application/json:
              example:
                message: "Login offline exitoso"
                token: "eyJhbGciOiJIUzI1NiIsIn..."
                user:
                  id: 42
                  email: "usuario@mail.com"
                  role: "admin"
        '400':
          description: PIN inválido o ubicación no coincide
          content:
            application/json:
              example:
                message: "PIN inválido o ubicación no coincide"
        '500':
          description: Error del servidor
          content:
            application/json:
              example:
                message: "Error del servidor"
