openapi: 3.0.0
info:
  title: API de Usuarios con Autenticación
  version: 1.0.0
  description: >
    API para gestión de usuarios con login, 2FA, recuperación de credenciales
    y administración de roles.
servers:
  - url: http://localhost:3000/api

paths:
  /users:
    get:
      summary: Lista todos los usuarios
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer }
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: integer }
                        email: { type: string }
                        role: { type: string }
                        phone: { type: string }

    post:
      summary: Crear un nuevo usuario
      description: >
        Crea un nuevo usuario y genera un PIN offline con código QR para autenticación sin conexión.
        El PIN y QR se envían por email y también se devuelven en la respuesta (solo para desarrollo).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - role
                - phone
              properties:
                email: { type: string, example: "usuario@ejemplo.com" }
                password: { type: string, example: "Password123!" }
                role: 
                  type: string
                  enum: [admin, editor, lector, user]
                  example: "user"
                phone: { type: string, example: "1234567890" }
      responses:
        '201':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: 
                    type: integer
                    example: 0
                  message: 
                    type: string
                    example: "Usuario registrado exitosamente"
                  user:
                    type: object
                    properties:
                      id: { type: integer, example: 42 }
                      email: { type: string, example: "usuario@ejemplo.com" }
                      role: { type: string, example: "user" }
                      phone: { type: string, example: "1234567890" }
                      created_at: { type: string, example: "2025-09-22T10:30:00.000Z" }
                  offlinePin:
                    type: string
                    description: "PIN offline de 6 dígitos para autenticación sin internet"
                    example: "829705"
                  qrCodeUrl:
                    type: string
                    description: "URL de imagen QR codificada en base64 con información de acceso offline"
                    example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA..."
          examples:
            desarrollo:
              summary: Respuesta para desarrollo
              value:
                code: 0
                message: "Usuario registrado exitosamente"
                user:
                  id: 42
                  email: "usuario@ejemplo.com"
                  role: "user"
                  phone: "1234567890"
                  created_at: "2025-09-22T10:30:00.000Z"
                offlinePin: "829705"
                qrCodeUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA..."
            produccion:
              summary: Respuesta para producción (sin datos sensibles)
              value:
                code: 0
                message: "Usuario registrado exitosamente. Se ha enviado el PIN offline por email."
                user:
                  id: 42
                  email: "usuario@ejemplo.com"
                  role: "user"
                  phone: "1234567890"
                  created_at: "2025-09-22T10:30:00.000Z"
        '400':
          description: Error en los datos de entrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 1 }
                  message: { type: string }
              examples:
                email-invalido:
                  value:
                    code: 1
                    message: "Correo electrónico inválido o dominio no permitido"
                email-existente:
                  value:
                    code: 1
                    message: "El correo ya existe"
                password-invalida:
                  value:
                    code: 1
                    message: "Contraseña inválida. Debe tener al menos 8 caracteres, una mayúscula, un número y un símbolo especial."
                telefono-invalido:
                  value:
                    code: 1
                    message: "Teléfono inválido"
                datos-faltantes:
                  value:
                    code: 1
                    message: "Email, password, role y phone son obligatorios"
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 1 }
                  message: { type: string }
                  error: { type: string }
              example:
                code: 1
                message: "Error al registrar usuario"
                error: "Error detail message"

  /users/{email}:
      put:
        summary: Actualiza un usuario por correo electrónico
        parameters:
          - in: path
            name: email
            required: true
            schema: { type: string }
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  newEmail: { type: string }
                  password: { type: string }
                  role: 
                    type: string
                    enum: [admin, editor, lector, user]
                  phone: { type: string }
        responses:
          '200':
            description: Usuario actualizado
          '404':
            description: Usuario no encontrado

      delete:
        summary: Elimina un usuario por correo electrónico
        parameters:
          - in: path
            name: email
            required: true
            schema: { type: string }
        responses:
          '200':
            description: Usuario eliminado
          '404':
            description: Usuario no encontrado

  /auth/login:
    post:
      summary: Login de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200':
          description: Login exitoso o requiere 2FA
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 0 }
                  message: { type: string }
                  requires2fa: { type: boolean }
                  token: { type: string }
        '401':
          description: Credenciales inválidas
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 1 }
                  message: { type: string }

  /auth/2fa/verify:
    post:
      summary: Verifica código OTP del 2FA
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tempToken, otp]
              properties:
                tempToken: { type: string }
                otp: { type: string }
      responses:
        '200':
          description: 2FA verificado
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 0 }
                  message: { type: string }
                  token: { type: string }
        '400':
          description: OTP inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 1 }
                  message: { type: string }

  /auth/password-reset/request:
    post:
      summary: Solicitar restablecimiento de contraseña
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email: { type: string }
                via: 
                  type: string
                  enum: [email, sms]
      responses:
        '200':
          description: Instrucciones enviadas
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 0 }
                  message: { type: string }

  /auth/password-reset/confirm:
    post:
      summary: Confirmar restablecimiento de contraseña
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token: { type: string }
                newPassword: { type: string }
      responses:
        '200':
          description: Contraseña cambiada
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 0 }
                  message: { type: string }
        '400':
          description: Token/OTP inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 1 }
                  message: { type: string }

  /auth/recover-username:
    post:
      summary: Recuperar nombre de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [emailOrPhone]
              properties:
                emailOrPhone: { type: string }
      responses:
        '200':
          description: Si existe, se envía username por email o SMS
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 0 }
                  message: { type: string }
  
  /auth/verify-offline:
    post:
      summary: Verifica PIN offline para login sin internet
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - offlinePin
                - lat
                - lng
              properties:
                userId:
                  type: number
                  example: 42
                offlinePin:
                  type: string
                  example: "829705"
                lat:
                  type: number
                  example: 19.4326
                lng:
                  type: number
                  example: -99.1332
      responses:
        '200':
          description: Login offline exitoso
          content:
            application/json:
              example:
                message: "Login offline exitoso"
                token: "eyJhbGciOiJIUzI1NiIsIn..."
                user:
                  id: 42
                  email: "usuario@mail.com"
                  role: "admin"
        '400':
          description: PIN inválido o ubicación no coincide
          content:
            application/json:
              example:
                message: "PIN inválido o ubicación no coincide"
        '500':
          description: Error del servidor
          content:
            application/json:
              example:
                message: "Error del servidor"


  /users/generate-offline-pin:
    post:
      summary: Generar PIN offline para usuario existente
      description: Genera un nuevo PIN offline con QR code para un usuario ya registrado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email: 
                  type: string
                  example: "usuario_existente@gmail.com"
      responses:
        '200':
          description: PIN offline generado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: integer, example: 0 }
                  message: { type: string }
                  user:
                    type: object
                    properties:
                      id: { type: integer }
                      email: { type: string }
                      role: { type: string }
                  offlinePin: { type: string }
                  qrCodeUrl: { type: string }
                  expiresAt: { type: string }
        '404':
          description: Usuario no encontrado
        '400':
          description: El usuario ya tiene un PIN activo
